import EnemyInterface from "@/app/Interfaces/EnemyInterface";

export const enemies: EnemyInterface[] = [
    { 
      id: 1,
      currentLife: 20, 
      initialLife: 20,
      currentPower: 4,
      currentShield: 0, 
      img: "/goblin_rastejante.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Goblin Rastejante',
      text: '',
      value: 1, 
      isEnemyFlashing: false,
      height: 150,
      width: 120 
    },
    {   
      id: 2,
      currentLife: 25, 
      initialLife: 25,
      currentPower: 6,
      currentShield: 0, 
      initialPower: 0,
      initialShield: 0,
      name: 'Lobo Selvagem',
      text: '',
      value: 2, 
      isEnemyFlashing: false,
      height: 180,
      width: 150, 
      img: "/lobo_selvagem.png",
    },
    { 
      id: 3, 
      currentLife: 40, 
      initialLife: 40, 
      currentPower: 8, 
      currentShield: 0, 
      img: "/esqueleto_reanimado.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Esqueleto Reanimado',
      text: '',
      value: 3, 
      isEnemyFlashing: false,
      height: 180,
      width: 150
    },
    { 
      id: 4, 
      currentLife: 35, 
      initialLife: 35, 
      currentPower: 9, 
      currentShield: 0, 
      img: "/mago_sombrio.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Mago Sombrio',
      text: '',
      value: 4, 
      isEnemyFlashing: false,
      height: 300,
      width: 250
    },
    { 
      id: 5, 
      currentLife: 70, 
      initialLife: 70, 
      currentPower: 11, 
      currentShield: 0, 
      img: "/ogro_montanha.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Ogro Montanha',
      text: '',
      value: 5, 
      isEnemyFlashing: false,
      height: 380,
      width: 320
    },
    { 
      id: 6, 
      currentLife: 60, 
      initialLife: 60, 
      currentPower: 15, 
      currentShield: 0, 
      img: "/cavaleiro_morte.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Cavaleiro da Morte',
      text: '',
      value: 6, 
      isEnemyFlashing: false,
      height: 350,
      width: 300
    },
    { 
      id: 7, 
      currentLife: 100, 
      initialLife: 100, 
      currentPower: 18, 
      currentShield: 0,
      img: "/dragao_jovem.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Dragão Jovem',
      text: '',
      value: 7, 
      isEnemyFlashing: false,
      height: 450,
      width: 400
    },
    { 
      id: 8, 
      currentLife: 80, 
      initialLife: 80, 
      currentPower: 20, 
      currentShield: 0, 
      img: "/demonio_chamas.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Demônio das Chamas',
      text: '',
      value: 8, 
      isEnemyFlashing: false,
      height: 380,
      width: 350
    },
    { 
      id: 9, 
      currentLife: 200, 
      initialLife: 200, 
      currentPower: 25, 
      currentShield: 0, 
      img: "/tirano_cosmico.png", 
      initialPower: 0,
      initialShield: 0,
      name: 'Tirano Cósmico',
      text: '',
      value: 9,
      isEnemyFlashing: false,
      height: 450,
      width: 400
    },
    { 
      id: 10, 
      currentLife: 500, 
      initialLife: 500, 
      currentPower: 30, 
      currentShield: 0, 
      img: "/deus_destruicao.png",
      initialPower: 0,
      initialShield: 0,
      name: 'Deus da Destruição',
      text: '',
      value: 10, 
      isEnemyFlashing: false,
      height: 380,
      width: 320
    },
  ];  